
package uk.hscic.itk.pds;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-18T14:05:52.846+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "ToolkitErrorInfo", targetNamespace = "urn:nhs-itk:ns:201005")
public class FaultResponse extends Exception {

    private uk.hscic.itk.pds.ToolkitErrorInfoStruct toolkitErrorInfo;

    public FaultResponse() {
        super();
    }

    public FaultResponse(String message) {
        super(message);
    }

    public FaultResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultResponse(String message, uk.hscic.itk.pds.ToolkitErrorInfoStruct toolkitErrorInfo) {
        super(message);
        this.toolkitErrorInfo = toolkitErrorInfo;
    }

    public FaultResponse(String message, uk.hscic.itk.pds.ToolkitErrorInfoStruct toolkitErrorInfo, Throwable cause) {
        super(message, cause);
        this.toolkitErrorInfo = toolkitErrorInfo;
    }

    public uk.hscic.itk.pds.ToolkitErrorInfoStruct getFaultInfo() {
        return this.toolkitErrorInfo;
    }
}
