package uk.hscic.itk.pds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-18T14:05:52.883+01:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "urn:nhs-itk:ns:201005", name = "verifyNHSNumber-v1-0_ptt")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VerifyNHSNumberV10Ptt {

    @WebMethod(operationName = "verifyNHSNumber-v1-0", action = "urn:nhs-itk:services:201005:verifyNHSNumber-v1-0")
    @WebResult(name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005", partName = "verifyNHSNumberResponse-v1-0")
    public DistributionEnvelopeType verifyNHSNumberV10(

            @WebParam(partName = "verifyNHSNumberRequest-v1-0", name = "DistributionEnvelope", targetNamespace = "urn:nhs-itk:ns:201005")
                    DistributionEnvelopeType verifyNHSNumberRequestV10
    ) throws FaultResponse;
}
