
package uk.gov.wildfyre.SMSP.itk;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import uk.hscic.itk.pds.FaultResponse;
import uk.hscic.itk.pds.GetNHSNumberV10;
import uk.hscic.itk.pds.GetNHSNumberV10Ptt;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-18T14:05:52.672+01:00
 * Generated source version: 3.3.2
 *
 */
public final class GetNHSNumber {

    private static final QName SERVICE_NAME = new QName("urn:nhs-itk:ns:201005", "getNHSNumber-v1-0");

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GetNHSNumberV10.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GetNHSNumberV10 ss = new GetNHSNumberV10(wsdlURL, SERVICE_NAME);
        GetNHSNumberV10Ptt port = ss.getGetNHSNumberV10PttPort();

        {
        System.out.println("Invoking getNHSNumberV10...");
        uk.hscic.itk.pds.DistributionEnvelopeType _getNHSNumberV10_getNHSNumberRequestV10 = null;
        try {
            uk.hscic.itk.pds.DistributionEnvelopeType _getNHSNumberV10__return = port.getNHSNumberV10(_getNHSNumberV10_getNHSNumberRequestV10);
            System.out.println("getNHSNumberV10.result=" + _getNHSNumberV10__return);

        } catch (FaultResponse e) {
            System.out.println("Expected exception: faultResponse has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
