
package uk.gov.wildfyre.SMSP.itk;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import uk.hscic.itk.pds.FaultResponse;
import uk.hscic.itk.pds.GetPatientDetailsBySearchV10;
import uk.hscic.itk.pds.GetPatientDetailsBySearchV10Ptt;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-18T14:05:52.709+01:00
 * Generated source version: 3.3.2
 *
 */
public final class GetPatientDetailsBySearch {

    private static final QName SERVICE_NAME = new QName("urn:nhs-itk:ns:201005", "getPatientDetailsBySearch-v1-0");

    private GetPatientDetailsBySearch() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GetPatientDetailsBySearchV10.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GetPatientDetailsBySearchV10 ss = new GetPatientDetailsBySearchV10(wsdlURL, SERVICE_NAME);
        GetPatientDetailsBySearchV10Ptt port = ss.getGetPatientDetailsBySearchV10PttPort();

        {
        System.out.println("Invoking getPatientDetailsBySearchV10...");
        uk.hscic.itk.pds.DistributionEnvelopeType _getPatientDetailsBySearchV10_getPatientDetailsBySearchRequestV10 = null;
        try {
            uk.hscic.itk.pds.DistributionEnvelopeType _getPatientDetailsBySearchV10__return = port.getPatientDetailsBySearchV10(_getPatientDetailsBySearchV10_getPatientDetailsBySearchRequestV10);
            System.out.println("getPatientDetailsBySearchV10.result=" + _getPatientDetailsBySearchV10__return);

        } catch (FaultResponse e) {
            System.out.println("Expected exception: faultResponse has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
