
package uk.gov.hscic.schema;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ToolkitErrorInfo", targetNamespace = "urn:nhs-itk:ns:201005")
public class FaultResponse
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ToolkitErrorInfoStruct faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultResponse(String message, ToolkitErrorInfoStruct faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FaultResponse(String message, ToolkitErrorInfoStruct faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: uk.gov.hscic.schema.ToolkitErrorInfoStruct
     */
    public ToolkitErrorInfoStruct getFaultInfo() {
        return faultInfo;
    }

}
