
package uk.gov.hscic.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getNHSNumber-v1-0", targetNamespace = "urn:nhs-itk:ns:201005", wsdlLocation = "file:/Development/DWP/smsp-adaptor/src/main/xsd/wsdl/PDSMiniServices-v1-0.wsdl")
public class GetNHSNumberV10
    extends Service
{

    private final static URL GETNHSNUMBERV10_WSDL_LOCATION;
    private final static WebServiceException GETNHSNUMBERV10_EXCEPTION;
    private final static QName GETNHSNUMBERV10_QNAME = new QName("urn:nhs-itk:ns:201005", "getNHSNumber-v1-0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Development/DWP/smsp-adaptor/src/main/xsd/wsdl/PDSMiniServices-v1-0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETNHSNUMBERV10_WSDL_LOCATION = url;
        GETNHSNUMBERV10_EXCEPTION = e;
    }

    public GetNHSNumberV10() {
        super(__getWsdlLocation(), GETNHSNUMBERV10_QNAME);
    }

    public GetNHSNumberV10(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETNHSNUMBERV10_QNAME, features);
    }

    public GetNHSNumberV10(URL wsdlLocation) {
        super(wsdlLocation, GETNHSNUMBERV10_QNAME);
    }

    public GetNHSNumberV10(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETNHSNUMBERV10_QNAME, features);
    }

    public GetNHSNumberV10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetNHSNumberV10(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetNHSNumberV10Ptt
     */
    @WebEndpoint(name = "getNHSNumber-v1-0_pttPort")
    public GetNHSNumberV10Ptt getGetNHSNumberV10PttPort() {
        return super.getPort(new QName("urn:nhs-itk:ns:201005", "getNHSNumber-v1-0_pttPort"), GetNHSNumberV10Ptt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetNHSNumberV10Ptt
     */
    @WebEndpoint(name = "getNHSNumber-v1-0_pttPort")
    public GetNHSNumberV10Ptt getGetNHSNumberV10PttPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:nhs-itk:ns:201005", "getNHSNumber-v1-0_pttPort"), GetNHSNumberV10Ptt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETNHSNUMBERV10_EXCEPTION!= null) {
            throw GETNHSNUMBERV10_EXCEPTION;
        }
        return GETNHSNUMBERV10_WSDL_LOCATION;
    }

}
