
package uk.gov.hscic.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getPatientDetailsByNHSNumber-v1-0", targetNamespace = "urn:nhs-itk:ns:201005", wsdlLocation = "file:/Development/wildfyre/smsp-adaptor/src/main/xsd/wsdl/PDSMiniServices-v1-0.wsdl")
public class GetPatientDetailsByNHSNumberV10
    extends Service
{

    private final static URL GETPATIENTDETAILSBYNHSNUMBERV10_WSDL_LOCATION;
    private final static WebServiceException GETPATIENTDETAILSBYNHSNUMBERV10_EXCEPTION;
    private final static QName GETPATIENTDETAILSBYNHSNUMBERV10_QNAME = new QName("urn:nhs-itk:ns:201005", "getPatientDetailsByNHSNumber-v1-0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Development/wildfyre/smsp-adaptor/src/main/xsd/wsdl/PDSMiniServices-v1-0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETPATIENTDETAILSBYNHSNUMBERV10_WSDL_LOCATION = url;
        GETPATIENTDETAILSBYNHSNUMBERV10_EXCEPTION = e;
    }

    public GetPatientDetailsByNHSNumberV10() {
        super(__getWsdlLocation(), GETPATIENTDETAILSBYNHSNUMBERV10_QNAME);
    }

    public GetPatientDetailsByNHSNumberV10(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETPATIENTDETAILSBYNHSNUMBERV10_QNAME, features);
    }

    public GetPatientDetailsByNHSNumberV10(URL wsdlLocation) {
        super(wsdlLocation, GETPATIENTDETAILSBYNHSNUMBERV10_QNAME);
    }

    public GetPatientDetailsByNHSNumberV10(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETPATIENTDETAILSBYNHSNUMBERV10_QNAME, features);
    }

    public GetPatientDetailsByNHSNumberV10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetPatientDetailsByNHSNumberV10(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetPatientDetailsByNHSNumberV10Ptt
     */
    @WebEndpoint(name = "getPatientDetailsByNHSNumber-v1-0_pttPort")
    public GetPatientDetailsByNHSNumberV10Ptt getGetPatientDetailsByNHSNumberV10PttPort() {
        return super.getPort(new QName("urn:nhs-itk:ns:201005", "getPatientDetailsByNHSNumber-v1-0_pttPort"), GetPatientDetailsByNHSNumberV10Ptt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPatientDetailsByNHSNumberV10Ptt
     */
    @WebEndpoint(name = "getPatientDetailsByNHSNumber-v1-0_pttPort")
    public GetPatientDetailsByNHSNumberV10Ptt getGetPatientDetailsByNHSNumberV10PttPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:nhs-itk:ns:201005", "getPatientDetailsByNHSNumber-v1-0_pttPort"), GetPatientDetailsByNHSNumberV10Ptt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETPATIENTDETAILSBYNHSNUMBERV10_EXCEPTION!= null) {
            throw GETPATIENTDETAILSBYNHSNUMBERV10_EXCEPTION;
        }
        return GETPATIENTDETAILSBYNHSNUMBERV10_WSDL_LOCATION;
    }

}
