
package uk.gov.hscic.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getPatientDetailsBySearch-v1-0", targetNamespace = "urn:nhs-itk:ns:201005", wsdlLocation = "file:/Development/DWP/smsp-adaptor/src/main/xsd/wsdl/PDSMiniServices-v1-0.wsdl")
public class GetPatientDetailsBySearchV10
    extends Service
{

    private final static URL GETPATIENTDETAILSBYSEARCHV10_WSDL_LOCATION;
    private final static WebServiceException GETPATIENTDETAILSBYSEARCHV10_EXCEPTION;
    private final static QName GETPATIENTDETAILSBYSEARCHV10_QNAME = new QName("urn:nhs-itk:ns:201005", "getPatientDetailsBySearch-v1-0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Development/DWP/smsp-adaptor/src/main/xsd/wsdl/PDSMiniServices-v1-0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETPATIENTDETAILSBYSEARCHV10_WSDL_LOCATION = url;
        GETPATIENTDETAILSBYSEARCHV10_EXCEPTION = e;
    }

    public GetPatientDetailsBySearchV10() {
        super(__getWsdlLocation(), GETPATIENTDETAILSBYSEARCHV10_QNAME);
    }

    public GetPatientDetailsBySearchV10(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETPATIENTDETAILSBYSEARCHV10_QNAME, features);
    }

    public GetPatientDetailsBySearchV10(URL wsdlLocation) {
        super(wsdlLocation, GETPATIENTDETAILSBYSEARCHV10_QNAME);
    }

    public GetPatientDetailsBySearchV10(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETPATIENTDETAILSBYSEARCHV10_QNAME, features);
    }

    public GetPatientDetailsBySearchV10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetPatientDetailsBySearchV10(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetPatientDetailsBySearchV10Ptt
     */
    @WebEndpoint(name = "getPatientDetailsBySearch-v1-0_pttPort")
    public GetPatientDetailsBySearchV10Ptt getGetPatientDetailsBySearchV10PttPort() {
        return super.getPort(new QName("urn:nhs-itk:ns:201005", "getPatientDetailsBySearch-v1-0_pttPort"), GetPatientDetailsBySearchV10Ptt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetPatientDetailsBySearchV10Ptt
     */
    @WebEndpoint(name = "getPatientDetailsBySearch-v1-0_pttPort")
    public GetPatientDetailsBySearchV10Ptt getGetPatientDetailsBySearchV10PttPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:nhs-itk:ns:201005", "getPatientDetailsBySearch-v1-0_pttPort"), GetPatientDetailsBySearchV10Ptt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETPATIENTDETAILSBYSEARCHV10_EXCEPTION!= null) {
            throw GETPATIENTDETAILSBYSEARCHV10_EXCEPTION;
        }
        return GETPATIENTDETAILSBYSEARCHV10_WSDL_LOCATION;
    }

}
