
package uk.gov.hscic.schema;



import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "verifyNHSNumber-v1-0", targetNamespace = "urn:nhs-itk:ns:201005", wsdlLocation = "file:/Development/DWP/smsp-adaptor/src/main/xsd/wsdl/PDSMiniServices-v1-0.wsdl")
public class VerifyNHSNumberV10
    extends Service
{

    private final static URL VERIFYNHSNUMBERV10_WSDL_LOCATION;
    private final static WebServiceException VERIFYNHSNUMBERV10_EXCEPTION;
    private final static QName VERIFYNHSNUMBERV10_QNAME = new QName("urn:nhs-itk:ns:201005", "verifyNHSNumber-v1-0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Development/DWP/smsp-adaptor/src/main/xsd/wsdl/PDSMiniServices-v1-0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERIFYNHSNUMBERV10_WSDL_LOCATION = url;
        VERIFYNHSNUMBERV10_EXCEPTION = e;
    }

    public VerifyNHSNumberV10() {
        super(__getWsdlLocation(), VERIFYNHSNUMBERV10_QNAME);
    }

    public VerifyNHSNumberV10(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERIFYNHSNUMBERV10_QNAME, features);
    }

    public VerifyNHSNumberV10(URL wsdlLocation) {
        super(wsdlLocation, VERIFYNHSNUMBERV10_QNAME);
    }

    public VerifyNHSNumberV10(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERIFYNHSNUMBERV10_QNAME, features);
    }

    public VerifyNHSNumberV10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerifyNHSNumberV10(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VerifyNHSNumberV10Ptt
     */
    @WebEndpoint(name = "verifyNHSNumber-v1-0_pttPort")
    public VerifyNHSNumberV10Ptt getVerifyNHSNumberV10PttPort() {
        return super.getPort(new QName("urn:nhs-itk:ns:201005", "verifyNHSNumber-v1-0_pttPort"), VerifyNHSNumberV10Ptt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerifyNHSNumberV10Ptt
     */
    @WebEndpoint(name = "verifyNHSNumber-v1-0_pttPort")
    public VerifyNHSNumberV10Ptt getVerifyNHSNumberV10PttPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:nhs-itk:ns:201005", "verifyNHSNumber-v1-0_pttPort"), VerifyNHSNumberV10Ptt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERIFYNHSNUMBERV10_EXCEPTION!= null) {
            throw VERIFYNHSNUMBERV10_EXCEPTION;
        }
        return VERIFYNHSNUMBERV10_WSDL_LOCATION;
    }

}
